// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructRAG.Store;

#nullable disable

namespace StructRAG.Store.Migrations
{
    [DbContext(typeof(StructRAGDbContext))]
    partial class StructRAGDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("structrag")
                .HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("StructRAG.Models.Substrate.Algorithm", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SourceChunkKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_chunk_key");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("steps");

                    b.HasKey("Key");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_Algorithms_DocumentId");

                    b.ToTable("algorithms", "structrag");
                });

            modelBuilder.Entity("StructRAG.Models.Substrate.CatalogueItem", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("attributes");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SourceChunkKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_chunk_key");

                    b.HasKey("Key");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_CatalogueItems_DocumentId");

                    b.ToTable("catalogue_items", "structrag");
                });

            modelBuilder.Entity("StructRAG.Models.Substrate.Entity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SourceChunkKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_chunk_key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Key");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_Entities_DocumentId");

                    b.ToTable("entities", "structrag");
                });

            modelBuilder.Entity("StructRAG.Models.Substrate.Event", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ParticipantEntityKeys")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("participant_entity_keys");

                    b.HasKey("Key");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_Events_DocumentId");

                    b.ToTable("events", "structrag");
                });

            modelBuilder.Entity("StructRAG.Models.Substrate.Evidence", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("ChunkKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("chunk_key");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("FactKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fact_key");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("quote");

                    b.HasKey("Key");

                    b.HasIndex("ChunkKey")
                        .HasDatabaseName("IX_Evidence_ChunkKey");

                    b.HasIndex("ChunkKey", "FactKey")
                        .HasDatabaseName("IX_Evidence_ChunkFact");

                    b.ToTable("evidence", "structrag");
                });

            modelBuilder.Entity("StructRAG.Models.Substrate.Fact", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("EvidenceChunkKeys")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence_chunk_keys");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("object");

                    b.Property<DateTimeOffset?>("OccurredOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Predicate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("predicate");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.HasKey("Key");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_Facts_DocumentId");

                    b.HasIndex("Predicate")
                        .HasDatabaseName("IX_Facts_Predicate");

                    b.HasIndex("Subject")
                        .HasDatabaseName("IX_Facts_Subject");

                    b.ToTable("facts", "structrag");
                });

            modelBuilder.Entity("StructRAG.Models.Substrate.SubstrateMetadata", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("ExtractionVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("extraction_version");

                    b.Property<DateTimeOffset>("LastBuilt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_built");

                    b.HasKey("DocumentId");

                    b.ToTable("substrate_metadata", "structrag");
                });
#pragma warning restore 612, 618
        }
    }
}
